package org.traccar.protocol;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.traccar.ProtocolTest;
import org.traccar.model.Position;

/**
 * Test for M2M Protocol Decoder
 * This test class supports both monolithic and microservices testing patterns
 */
public class M2mProtocolDecoderTest extends ProtocolTest {

    /**
     * Basic protocol decoder test that works in both monolithic and microservices environments
     */
    @Test
    public void testDecode() throws Exception {
        var decoder = inject(new M2mProtocolDecoder(null));

        verifyNull(decoder, binary(
                "235A3C2A2624215C287D70212A21254C7C6421220B0B0B"));

        verifyPosition(decoder, binary(
                "A6E12C2AAADA4628326B2059576E30202A2FE85D20200B"));
    }

    /**
     * Test for protocol integration with message broker
     * This test is only enabled when running in microservices mode
     */
    @Test
    @EnabledIfSystemProperty(named = "test.microservices.enabled", matches = "true")
    public void testMessageBrokerIntegration() throws Exception {
        // Use injectWithMessageBroker to get a decoder configured for message broker testing
        var decoder = injectWithMessageBroker(new M2mProtocolDecoder(null));
        
        // Create a test position
        Position position = position(decoder, binary(
                "A6E12C2AAADA4628326B2059576E30202A2FE85D20200B"));
        
        // Verify position was published to message broker
        verifyPositionPublished(position);
    }

    /**
     * Test for protocol handling across service boundaries
     * This test is only enabled when running in microservices mode
     */
    @Test
    @EnabledIfSystemProperty(named = "test.microservices.enabled", matches = "true")
    public void testCrossServiceHandling() throws Exception {
        // Use injectWithMessageBroker to get a decoder configured for message broker testing
        var decoder = injectWithMessageBroker(new M2mProtocolDecoder(null));
        
        // Create a test position
        Position position = position(decoder, binary(
                "A6E12C2AAADA4628326B2059576E30202A2FE85D20200B"));
        
        // Verify position was processed by position service
        verifyPositionProcessed(position);
        
        // Verify events were generated by event service
        verifyEventsGenerated(position);
    }
}