package org.traccar.protocol;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.mockito.Mockito;
import org.traccar.ProtocolTest;
import org.traccar.model.Position;

/**
 * Test for NTO protocol decoder.
 * This test is designed to support both monolithic and microservices architectures.
 * 
 * The test includes:
 * 1. Basic protocol decoding test (works in both architectures)
 * 2. Message broker integration test (microservices only)
 * 3. Cross-service boundary test (microservices only)
 * 
 * For microservices testing, set the system property: -Dtest.microservices=true
 */
public class NtoProtocolDecoderTest extends ProtocolTest {

    /**
     * Basic protocol decoding test that works in both monolithic and microservices architectures.
     * This test verifies that the NTO protocol decoder correctly parses position data from the device message.
     */
    @Test
    public void testDecode() throws Exception {
        var decoder = inject(new NtoProtocolDecoder(null));

        verifyPosition(decoder, text(
                "^NB,880002023090601,N00,050923,233519,V,N,2236.1994,E,11315.4645,5,0,000000000000,460:00:0:75217090,-04:00,,1693971319,31,2DA5"),
                position("2023-09-05 23:35:19.000", false, 22.60332, 113.25774));
    }

    /**
     * Test for message broker integration in microservices architecture.
     * This test verifies that decoded positions are properly published to the message broker.
     * It will be skipped when running in monolithic mode.
     * 
     * In the microservices architecture, the Protocol Service publishes decoded positions
     * to a message broker topic for consumption by the Position Service.
     */
    @Test
    @EnabledIfSystemProperty(named = "test.microservices", matches = "true")
    public void testMessageBrokerIntegration() throws Exception {
        var decoder = inject(new NtoProtocolDecoder(null));
        
        // Mock the message broker producer
        var messageProducer = Mockito.mock(org.traccar.messaging.MessageProducer.class);
        inject(messageProducer);
        
        // Process the message
        Position position = decoder.decode(null, null, text(
                "^NB,880002023090601,N00,050923,233519,V,N,2236.1994,E,11315.4645,5,0,000000000000,460:00:0:75217090,-04:00,,1693971319,31,2DA5"));
        
        // Verify position was created
        verifyPosition(position, "2023-09-05 23:35:19.000", false, 22.60332, 113.25774);
        
        // Verify message was published to broker
        Mockito.verify(messageProducer).publish(Mockito.eq("positions"), Mockito.eq(position));
    }
    
    /**
     * Test for cross-service boundary handling in microservices architecture.
     * This test verifies that positions are properly processed across service boundaries.
     * It will be skipped when running in monolithic mode.
     * 
     * In the microservices architecture, after the Protocol Service decodes a position:
     * 1. The Position Service processes and enriches the position data
     * 2. The Event Service evaluates the position against configured rules
     * 
     * This test ensures that these cross-service interactions work correctly.
     */
    @Test
    @EnabledIfSystemProperty(named = "test.microservices", matches = "true")
    public void testCrossServiceHandling() throws Exception {
        var decoder = inject(new NtoProtocolDecoder(null));
        
        // Mock the position service client
        var positionServiceClient = Mockito.mock(org.traccar.client.PositionServiceClient.class);
        inject(positionServiceClient);
        
        // Mock the event service client
        var eventServiceClient = Mockito.mock(org.traccar.client.EventServiceClient.class);
        inject(eventServiceClient);
        
        // Process the message
        Position position = decoder.decode(null, null, text(
                "^NB,880002023090601,N00,050923,233519,V,N,2236.1994,E,11315.4645,5,0,000000000000,460:00:0:75217090,-04:00,,1693971319,31,2DA5"));
        
        // Verify position was created
        verifyPosition(position, "2023-09-05 23:35:19.000", false, 22.60332, 113.25774);
        
        // Verify position was processed by position service
        Mockito.verify(positionServiceClient).processPosition(Mockito.eq(position));
        
        // Verify events were generated by event service
        Mockito.verify(eventServiceClient).checkEvents(Mockito.eq(position));
    }
}