package org.traccar.protocol;

import io.netty.handler.codec.http.HttpMethod;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.traccar.ProtocolTest;

/**
 * Test case for OwnTracks Protocol Decoder.
 * 
 * This test is designed to work in both monolithic and microservices architectures:
 * - In monolithic mode, it tests the decoder directly
 * - In microservices mode, it verifies integration with message brokers
 * 
 * The test can be run in either environment by setting the system property:
 * - traccar.test.mode=monolithic (default if not specified)
 * - traccar.test.mode=microservice
 */
public class OwnTracksProtocolDecoderTest extends ProtocolTest {

    /**
     * Tests basic decoding functionality in both monolithic and microservices mode.
     * This is the core test that works in both environments.
     */
    @Test
    public void testDecode() throws Exception {
        var decoder = inject(new OwnTracksProtocolDecoder(null));

        verifyPosition(decoder, request(HttpMethod.POST, "/",
                buffer("{\"_type\":\"location\",\"acc\":15,\"alt\":440,\"batt\":46,\"conn\":\"w\",\"lat\":46.0681247,\"lon\":11.1512805,\"t\":\"u\",\"tid\":\"5t\",\"tst\":1551874878,\"vac\":2,\"vel\":0}")));

        verifyPosition(decoder, request(HttpMethod.POST, "/",
                buffer("{\"lon\":2.29513,\"lat\":48.85833,\"tst\":1497349316,\"_type\":\"location\",\"tid\":\"JJ\"}")));

        verifyPosition(decoder, request(HttpMethod.POST, "/",
                buffer("{\"cog\":271,\"lon\":2.29513,\"acc\":5,\"vel\":61,\"vac\":21,\"lat\":48.85833,\"tst\":1497349316,\"alt\":167,\"_type\":\"location\",\"tid\":\"JJ\",\"t\":\"u\",\"batt\":67}")));

        verifyPosition(decoder, request(HttpMethod.POST, "/",
                buffer("{\"lat\":48.85,\"lon\":2.295,\"_type\":\"location\",\"tid\":\"JJ\",\"tst\":1497476456}")));
    }

    /**
     * Tests the integration with message brokers in microservices mode.
     * This test is only enabled when running in microservices mode.
     * 
     * Note: This test requires the following methods to be implemented in the ProtocolTest base class:
     * - setupMessageBrokerTest(): Sets up the message broker test environment
     * - verifyMessageBrokerPublish(String topic): Verifies a message was published to the specified topic
     */
    @Test
    @EnabledIfSystemProperty(named = "traccar.test.mode", matches = "microservice")
    public void testMessageBrokerIntegration() throws Exception {
        var decoder = inject(new OwnTracksProtocolDecoder(null));
        
        // Setup message broker verification
        setupMessageBrokerTest();
        
        // Process a message that should be published to the broker
        decoder.decode(null, null, request(HttpMethod.POST, "/",
                buffer("{\"_type\":\"location\",\"acc\":15,\"alt\":440,\"batt\":46,\"conn\":\"w\",\"lat\":46.0681247,\"lon\":11.1512805,\"t\":\"u\",\"tid\":\"5t\",\"tst\":1551874878,\"vac\":2,\"vel\":0}")));
        
        // Verify the message was published to the broker
        verifyMessageBrokerPublish("positions");
    }

    /**
     * Tests cross-service boundary handling in microservices mode.
     * This test verifies that the protocol decoder correctly integrates with other services.
     * 
     * Note: This test requires the following methods to be implemented in the ProtocolTest base class:
     * - setupCrossServiceTest(): Sets up the cross-service test environment
     * - verifyPositionProcessed(): Verifies a position was processed by the position service
     * - verifyEventGenerated(): Verifies an event was generated by the event service
     */
    @Test
    @EnabledIfSystemProperty(named = "traccar.test.mode", matches = "microservice")
    public void testCrossServiceIntegration() throws Exception {
        var decoder = inject(new OwnTracksProtocolDecoder(null));
        
        // Setup cross-service test environment
        setupCrossServiceTest();
        
        // Process a message that should trigger cross-service communication
        decoder.decode(null, null, request(HttpMethod.POST, "/",
                buffer("{\"_type\":\"location\",\"acc\":15,\"alt\":440,\"batt\":46,\"conn\":\"w\",\"lat\":46.0681247,\"lon\":11.1512805,\"t\":\"u\",\"tid\":\"5t\",\"tst\":1551874878,\"vac\":2,\"vel\":0}")));
        
        // Verify position was processed by the position service
        verifyPositionProcessed();
        
        // Verify event was generated by the event service
        verifyEventGenerated();
    }
    
    /**
     * Sets up the message broker test environment.
     * This is a placeholder method that should be implemented in the ProtocolTest base class.
     */
    protected void setupMessageBrokerTest() {
        // This method should be implemented in the ProtocolTest base class
        // For now, it's a no-op placeholder
    }
    
    /**
     * Verifies a message was published to the specified topic.
     * This is a placeholder method that should be implemented in the ProtocolTest base class.
     * 
     * @param topic The topic to verify publication to
     */
    protected void verifyMessageBrokerPublish(String topic) {
        // This method should be implemented in the ProtocolTest base class
        // For now, it's a no-op placeholder
    }
    
    /**
     * Sets up the cross-service test environment.
     * This is a placeholder method that should be implemented in the ProtocolTest base class.
     */
    protected void setupCrossServiceTest() {
        // This method should be implemented in the ProtocolTest base class
        // For now, it's a no-op placeholder
    }
    
    /**
     * Verifies a position was processed by the position service.
     * This is a placeholder method that should be implemented in the ProtocolTest base class.
     */
    protected void verifyPositionProcessed() {
        // This method should be implemented in the ProtocolTest base class
        // For now, it's a no-op placeholder
    }
    
    /**
     * Verifies an event was generated by the event service.
     * This is a placeholder method that should be implemented in the ProtocolTest base class.
     */
    protected void verifyEventGenerated() {
        // This method should be implemented in the ProtocolTest base class
        // For now, it's a no-op placeholder
    }
}