package org.traccar.protocol;

import io.netty.handler.codec.http.HttpMethod;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.traccar.ProtocolTest;
import org.traccar.model.Position;

import java.util.List;

/**
 * Test for Piligrim Protocol Decoder
 * This test class supports both monolithic and microservices testing approaches
 */
public class PiligrimProtocolDecoderTest extends ProtocolTest {

    /**
     * Basic decoder test for backward compatibility with monolithic architecture
     */
    @Test
    public void testDecode() throws Exception {

        var decoder = inject(new PiligrimProtocolDecoder(null));
        
        verifyPositions(decoder, request(HttpMethod.POST,
                "/bingps?imei=868204005544720&csq=18&vout=00&vin=4050&dataid=00000000",
                binary("fff2200d4110061a32354f3422310062000a0005173b0000a101000300005e00fff2200d4110100932354f2b22310042000b000e173b00009f01000700006000")));

        verifyPosition(decoder, request(HttpMethod.POST,
                "/push.do",
                buffer("&phoneNumber=%2B+78000000000&message=ALARM KEY; $GPRMC,180752.000,A,5314.0857,N,03421.8173,E,0.00,104.74,220722,,,A,V* 29,05; GSM: 250-01 0b54-0519,1c30,3e96,3ebe,412e 25;  S; Batt: 405,M")));

    }
    
    /**
     * Microservices integration test that verifies protocol handling with message broker
     * This test is tagged for selective execution in microservices environment
     */
    @Test
    @Tag("microservice")
    public void testDecodeWithMessageBroker() throws Exception {
        // This test will be implemented when running in microservices mode
        // It will verify that decoded positions are properly published to the message broker
        
        // Skip test in monolithic mode
        if (!isMicroservicesEnabled()) {
            return;
        }
        
        var decoder = inject(new PiligrimProtocolDecoder(null));
        
        // Decode the message
        var result = decoder.decode(null, null, request(HttpMethod.POST,
                "/bingps?imei=868204005544720&csq=18&vout=00&vin=4050&dataid=00000000",
                binary("fff2200d4110061a32354f3422310062000a0005173b0000a101000300005e00fff2200d4110100932354f2b22310042000b000e173b00009f01000700006000")));
        
        // Verify positions were decoded correctly
        assertNotNull(result);
        assertTrue(result instanceof List);
        
        @SuppressWarnings("unchecked")
        List<Position> positions = (List<Position>) result;
        assertFalse(positions.isEmpty());
        
        // In microservices mode, this would verify that positions were published to the message broker
        // verifyMessageBrokerPublish(positions, "positions");
    }
    
    /**
     * Cross-service boundary test that verifies protocol handling across services
     * This test is tagged for selective execution in microservices environment
     */
    @Test
    @Tag("integration")
    public void testCrossServiceBoundary() throws Exception {
        // This test will be implemented when running in microservices mode
        // It will verify that positions flow correctly from Protocol Service to Position Service
        
        // Skip test in monolithic mode
        if (!isMicroservicesEnabled()) {
            return;
        }
        
        var decoder = inject(new PiligrimProtocolDecoder(null));
        
        // Decode the message
        var result = decoder.decode(null, null, request(HttpMethod.POST,
                "/push.do",
                buffer("&phoneNumber=%2B+78000000000&message=ALARM KEY; $GPRMC,180752.000,A,5314.0857,N,03421.8173,E,0.00,104.74,220722,,,A,V* 29,05; GSM: 250-01 0b54-0519,1c30,3e96,3ebe,412e 25;  S; Batt: 405,M")));
        
        // Verify position was decoded correctly
        assertNotNull(result);
        assertTrue(result instanceof Position);
        
        // In microservices mode, this would verify that the position was processed by the Position Service
        // and that events were generated by the Event Service if applicable
        // verifyPositionProcessed((Position) result);
        // verifyEventGenerated((Position) result, "alarm");
    }
    
    /**
     * Helper method to determine if running in microservices mode
     * This would be implemented to check environment or configuration
     */
    private boolean isMicroservicesEnabled() {
        // In a real implementation, this would check for environment variables,
        // configuration settings, or service discovery presence to determine
        // if running in microservices mode
        return System.getProperty("traccar.microservices.enabled", "false").equals("true");
    }
}