package org.traccar.protocol;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.traccar.ProtocolTest;
import org.traccar.model.Position;

/**
 * Test for ThinkRace protocol decoder.
 * This test is designed to work in both monolithic and microservices environments.
 */
public class ThinkRaceProtocolDecoderTest extends ProtocolTest {

    @Test
    public void testDecode() throws Exception {
        var decoder = inject(new ThinkRaceProtocolDecoder(null));

        verifyNull(decoder, binary(
                "48415349483031343730303134382C8000100134363030303134363139363239343806FF"));

        verifyPosition(decoder, binary(
                "48415349483031343730303134382C90001755701674D70155466406CBB813003D24A410F5000000770B4C"));
    }

    /**
     * Test for message broker integration.
     * This test is only enabled when running in the microservices environment.
     * It verifies that decoded positions are properly published to the message broker.
     */
    @Test
    @EnabledIfSystemProperty(named = "test.microservices", matches = "true")
    public void testMessageBrokerIntegration() throws Exception {
        var decoder = inject(new ThinkRaceProtocolDecoder(null));
        
        // Decode a position message
        Position position = decoder.decode(null, null, binary(
                "48415349483031343730303134382C90001755701674D70155466406CBB813003D24A410F5000000770B4C"));
        
        // Verify the position was published to the message broker
        // This method is implemented in the ProtocolTest base class for microservices testing
        if (position != null) {
            verifyPositionPublished(position);
        }
    }

    /**
     * Test for cross-service boundary handling.
     * This test is only enabled when running in the microservices environment.
     * It verifies that positions are properly processed across service boundaries,
     * including position processing and event generation.
     */
    @Test
    @EnabledIfSystemProperty(named = "test.microservices", matches = "true")
    public void testCrossServiceBoundary() throws Exception {
        var decoder = inject(new ThinkRaceProtocolDecoder(null));
        
        // Decode a position message
        Position position = decoder.decode(null, null, binary(
                "48415349483031343730303134382C90001755701674D70155466406CBB813003D24A410F5000000770B4C"));
        
        // Verify position processing across service boundaries
        if (position != null) {
            // Verify the position was processed by the position service
            verifyPositionProcessed(position);
            
            // Verify events were generated by the event service
            verifyEventsGenerated(position);
        }
    }
}